version: "3.3"
services:

  db:
    restart: always
    image: clickhouse/clickhouse-server
    environment:
      - CLICKHOUSE_USER=bspauto
      - CLICKHOUSE_PASSWORD=bspauto
      - CLICKHOUSE_DB=bspauto
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
    ports:
      - "8123:8123"
      - "9000:9000"
    ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
