"""First revision

Revision ID: f71ee231a6dc
Revises:
Create Date: 2019-04-17 13:53:32.978401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
import clickhouse_sqlalchemy
from clickhouse_sqlalchemy import engines


# revision identifiers, used by Alembic.
revision = "f71ee231a6dc"
down_revision = "6e523d653806"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", clickhouse_sqlalchemy.types.common.UUID(), nullable=False, server_default=text("generateUUIDv4()")),
        sa.Column("full_name", clickhouse_sqlalchemy.types.common.String(), nullable=True),
        sa.Column("email", clickhouse_sqlalchemy.types.common.String(), nullable=True),
        sa.Column("hashed_password", clickhouse_sqlalchemy.types.common.String(), nullable=True),
        sa.Column("is_active", clickhouse_sqlalchemy.types.common.Boolean(), nullable=True),
        sa.Column("is_superuser", clickhouse_sqlalchemy.types.common.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        engines.ReplacingMergeTree(order_by=('email'))
    )
    op.create_table(
        "item",
        sa.Column("id", clickhouse_sqlalchemy.types.common.UUID(), nullable=False, server_default=text("generateUUIDv4()")),
        sa.Column("title", clickhouse_sqlalchemy.types.common.String(), nullable=True),
        sa.Column("description", clickhouse_sqlalchemy.types.common.String(), nullable=True),
        sa.Column("owner_id", clickhouse_sqlalchemy.types.common.UUID(), nullable=True),
        # sa.ForeignKeyConstraint(["owner_id"], ["user.id"],),
        sa.PrimaryKeyConstraint("id"),
        engines.ReplacingMergeTree(order_by=('id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("item")
    op.drop_table("user")
    # ### end Alembic commands ###
